### ISSUE TITLE
Show discord and loyalty points earned on _a userinfo command

### ISSUE THREAD

**Issue by Leslie-fay** [branjos/Clan_Bot-Wiki#70]
Discord could be true false since should only receive once
Loyalty count by months

**Comment by branjos** [comment]
![image](https://user-images.githubusercontent.com/10274142/35228613-204d5f9a-ff5f-11e7-8def-b48bde6de615.png)

Circled in blue is loyalty points, circled in red is discord use points. I didn't want to add too much data to the _a userinfo command simply because it'll clutter it more than it already is. I'm open to changing the looks of these values, but the data is already there

**Comment by Leslie-fay** [comment]
oh but wait isn't validate just means they have validated their account, not that they have been given points for being in discord. Or is discord points only given when validated? I guess I don't know how that works

**Comment by branjos** [comment]
Yes, Discord Points are given if the user is validated with the bot. This was the only semi-automated way I could prove who is and is not using discord since rsn and discord name.

**Comment by branjos** [comment]
Going to close because it is there already. Will revisit with website.
